remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
include: ["_pages"]
title: "Same But Different"
subtitle: "A blog by Marwan Ajala"
name: "Marwan Ajala"
repository: "serizawan/serizawan"
logo: "/assets/images/home/logo.png"
breadcrumbs: true
search: true
lunr:
  search_within_pages: true
description: "Writings about problem solving, working methodologies, python, mathematics, table tennis..."
baseurl: ""
url: ""
github_username: "serizawan"
paginate: 5
author:
  name: "Marwan Ajala"
  avatar: "/assets/images/home/me.jpg"
  bio: "Hey, I am currently working at SAP SuccessFactors as a senior Software Engineer."
  location : "Paris, France"
  links:
    - label: "My Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/serizawan"
comments:
  provider: "facebook"
  facebook:
    num_posts: 5
    colorscheme: "dark"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      read_time: true
      comments: false
      share: true
      related: true
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true